[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"


[metadata.heroku]
  root-package = "github.com/JrFarias/go-clean"
  go-version = "go1.10.2"
  ensure = "false"
  install = [ "./cmd/...", "./foo" ]
  additional-tools = ["github.com/jinzhu/gorm","github.com/gin-gonic/gin"]
